// Fake data for the prototype. Every person, company and event here is fictional.
// Program names match NEXT's public programs; cohort assignments are made up.

window.DATA = (function () {
  const hoursAgo = (h) => new Date(Date.now() - h * 3600 * 1000).toISOString();

  const TAXONOMY = {
    badges: ["Founder", "Alumni", "Current participant", "NEXT Staff", "Board"],
    programs: ["NEXT 36", "NEXT Founders", "NEXT AI"],
    sectors: ["AI / ML", "B2B SaaS", "Biotech", "Climate", "Consumer", "Edtech", "Fintech", "Hardware", "Health tech", "Legal tech", "Marketplaces"],
    skills: ["Engineering leadership", "Enterprise sales", "Fundraising", "Go-to-market", "Hiring", "International expansion", "Legal", "Marketing", "Operations", "Partnerships", "Pricing", "Product", "Regulatory"],
    lookingFor: ["Advice", "Co-founder", "Customers", "Hires", "Investors", "Partners"],
    openTo: ["Coffee chats", "Intro requests", "Mentoring"],
    countries: ["Canada", "United States"],
    channels: ["General", "Announcements", "Fundraising", "Hiring", "Intro requests", "Events", "Legal & finance", "Product & tech", "Sales & marketing"],
  };

  const people = [
    {
      id: "maya-okonkwo", name: "Maya Okonkwo", pronouns: "she/her", city: "Waterloo", region: "ON", country: "Canada",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT Founders", year: 2021 }],
      headline: "Co-founder @ Tidepool Health, building scheduling software for community clinics",
      about: "Former ER nurse turned founder. We help community health clinics cut no-shows and wait times. 40 clinics across Ontario and Manitoba.",
      ask: "Selling to public-sector health buyers, running a seed round in Canada, hiring a first sales lead, SR&ED claims.",
      sectors: ["Health tech", "B2B SaaS"], skills: ["Fundraising", "Enterprise sales", "Hiring", "Regulatory"],
      lookingFor: { picks: ["Investors", "Advice"], text: "Series A investors who know health; advice on US expansion.", updated: "3 weeks ago" },
      openTo: ["Coffee chats", "Intro requests"],
      companies: [{ name: "Tidepool Health", role: "Co-founder & CEO", years: "2021 – present", status: "Active", site: "tidepool.example" }],
      role: "CEO, Tidepool Health", links: ["linkedin.com/in/maya-okonkwo-example", "tidepool.example"], updatedDays: 21,
    },
    {
      id: "daniel-kwan", name: "Daniel Kwan", pronouns: "he/him", city: "Toronto", region: "ON", country: "Canada",
      badges: ["Alumni"], programs: [{ name: "NEXT 36", year: 2019 }],
      headline: "VP Sales @ Northwind Care. Scaled hospital sales from 2 to 60 accounts",
      about: "Ten years selling software into Canadian hospitals and health networks. I like helping founders with their first enterprise deals.",
      ask: "Hospital procurement, long sales cycles, building a sales team, pricing enterprise contracts.",
      sectors: ["Health tech", "B2B SaaS"], skills: ["Enterprise sales", "Go-to-market", "Pricing", "Hiring"],
      lookingFor: { picks: ["Hires"], text: "Hiring two sales engineers in Toronto.", updated: "1 month ago" },
      openTo: ["Coffee chats", "Intro requests", "Mentoring"],
      companies: [],
      role: "VP Sales, Northwind Care", links: ["linkedin.com/in/daniel-kwan-example"], updatedDays: 34,
    },
    {
      id: "priya-shah", name: "Priya Shah", pronouns: "she/her", city: "Toronto", region: "ON", country: "Canada",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT AI", year: 2022 }],
      headline: "Co-founder & CEO @ Ledgerline, AI bookkeeping for small accounting firms",
      about: "Ex-KPMG auditor. Ledgerline automates month-end close for firms with 10 to 50 staff. Raised a seed round in 2024.",
      ask: "Selling to accountants, raising a seed round, fintech compliance, using LLMs in regulated work.",
      sectors: ["Fintech", "AI / ML"], skills: ["Fundraising", "Product", "Regulatory"],
      lookingFor: { picks: ["Customers"], text: "Intros to accounting firms with 10 to 50 staff.", updated: "2 weeks ago" },
      openTo: ["Intro requests"],
      companies: [{ name: "Ledgerline", role: "Co-founder & CEO", years: "2022 – present", status: "Active", site: "ledgerline.example" }],
      role: "CEO, Ledgerline", links: ["linkedin.com/in/priya-shah-example"], updatedDays: 14,
    },
    {
      id: "jordan-lee", name: "Jordan Lee", pronouns: "they/them", city: "Toronto", region: "ON", country: "Canada",
      badges: ["NEXT Staff"], programs: [],
      headline: "Community Lead at NEXT. Alumni events and programming",
      about: "I run alumni events and look after this platform's community. Message me with event ideas or if something here isn't working.",
      ask: "Hosting an alumni event, finding a venue, getting connected to someone at NEXT.",
      sectors: [], skills: ["Partnerships", "Operations"],
      lookingFor: { picks: ["Partners"], text: "Venues in Montréal and Vancouver for alumni events.", updated: "1 week ago" },
      openTo: ["Coffee chats", "Intro requests"],
      companies: [],
      role: "Community Lead, NEXT Canada", links: [], updatedDays: 7,
    },
    {
      id: "etienne-gagnon", name: "Étienne Gagnon", pronouns: "he/him", city: "Montréal", region: "QC", country: "Canada",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT Founders", year: 2018 }],
      headline: "Founder @ Voltaire Grid, battery storage for small utilities",
      about: "Second-time founder. Sold Parcel9 (last-mile logistics) in 2020. Now building grid-scale storage for municipal utilities in Québec and New England.",
      ask: "Hardware manufacturing, selling to utilities, government grants for climate tech, selling a company.",
      sectors: ["Climate", "Hardware"], skills: ["Fundraising", "Operations", "International expansion", "Engineering leadership"],
      lookingFor: { picks: ["Advice", "Partners"], text: "Contract manufacturers for battery enclosures.", updated: "5 months ago" },
      openTo: ["Coffee chats", "Mentoring"],
      companies: [
        { name: "Voltaire Grid", role: "Founder & CEO", years: "2021 – present", status: "Active", site: "voltairegrid.example" },
        { name: "Parcel9", role: "Co-founder", years: "2016 – 2020", status: "Acquired", site: "parcel9.example" },
      ],
      role: "CEO, Voltaire Grid", links: ["linkedin.com/in/etienne-gagnon-example"], updatedDays: 150,
    },
    {
      id: "aisha-rahman", name: "Aisha Rahman", pronouns: "she/her", city: "Vancouver", region: "BC", country: "Canada",
      badges: ["Founder", "Current participant"], programs: [{ name: "NEXT AI", year: 2026 }],
      headline: "Co-founder @ Kitewing, computer vision for construction site safety",
      about: "Our cameras spot safety hazards on construction sites before incidents happen. Piloting with three general contractors in BC.",
      ask: "Computer vision in the field, selling to construction companies, pilot contracts.",
      sectors: ["AI / ML", "Hardware"], skills: ["Product", "Engineering leadership"],
      lookingFor: { picks: ["Co-founder", "Investors"], text: "Technical co-founder with robotics or embedded experience; pre-seed investors.", updated: "4 days ago" },
      openTo: ["Coffee chats", "Intro requests"],
      companies: [{ name: "Kitewing", role: "Co-founder & CEO", years: "2025 – present", status: "Active", site: "kitewing.example" }],
      role: "CEO, Kitewing", links: ["kitewing.example"], updatedDays: 4,
    },
    {
      id: "sam-whitehorse", name: "Sam Whitehorse", pronouns: "he/him", city: "Calgary", region: "AB", country: "Canada",
      badges: ["Founder", "Alumni", "Board"], programs: [{ name: "NEXT 36", year: 2015 }],
      headline: "Angel investor. Founded Prairie Freight (acquired 2021)",
      about: "Built a freight marketplace for Prairie shippers and sold it in 2021. Now I invest in early-stage marketplaces and logistics, and sit on NEXT's board.",
      ask: "Two-sided marketplaces, pricing, selling a company, angel investing, board governance.",
      sectors: ["Marketplaces", "Fintech"], skills: ["Fundraising", "Pricing", "Operations"],
      lookingFor: { picks: ["Advice"], text: "Meeting founders in logistics and marketplaces.", updated: "2 months ago" },
      openTo: ["Coffee chats", "Intro requests", "Mentoring"],
      companies: [{ name: "Prairie Freight", role: "Founder & CEO", years: "2014 – 2021", status: "Acquired", site: "prairiefreight.example" }],
      role: "Angel investor", links: ["linkedin.com/in/sam-whitehorse-example"], updatedDays: 60,
    },
    {
      id: "lena-novak", name: "Lena Novak", pronouns: "she/her", city: "Ottawa", region: "ON", country: "Canada",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT Founders", year: 2020 }],
      headline: "CEO @ Brightpath Learning, reading support for grades 1–4",
      about: "Brightpath is used by 120 schools in Ontario. Former teacher. Spent a lot of time learning how school boards buy.",
      ask: "Selling to school boards, education marketing, partnerships with non-profits.",
      sectors: ["Edtech", "Consumer"], skills: ["Marketing", "Go-to-market", "Partnerships"],
      lookingFor: { picks: ["Partners", "Customers"], text: "School boards outside Ontario, especially Alberta and BC.", updated: "3 weeks ago" },
      openTo: ["Intro requests"],
      companies: [{ name: "Brightpath Learning", role: "Founder & CEO", years: "2019 – present", status: "Active", site: "brightpath.example" }],
      role: "CEO, Brightpath Learning", links: ["brightpath.example"], updatedDays: 21,
    },
    {
      id: "marcus-bell", name: "Marcus Bell", pronouns: "he/him", city: "Halifax", region: "NS", country: "Canada",
      badges: ["Alumni"], programs: [{ name: "NEXT AI", year: 2023 }],
      headline: "ML engineer @ Harbourline Robotics, exploring a climate-tech idea",
      about: "I build perception models for underwater robots. Thinking about starting something in ocean monitoring.",
      ask: "Robotics perception, training models on small datasets, working in Atlantic Canada.",
      sectors: ["AI / ML", "Hardware", "Climate"], skills: ["Engineering leadership", "Product"],
      lookingFor: { picks: ["Co-founder", "Advice"], text: "A business-side co-founder for an ocean monitoring idea.", updated: "1 week ago" },
      openTo: ["Coffee chats"],
      companies: [],
      role: "ML engineer, Harbourline Robotics", links: ["linkedin.com/in/marcus-bell-example"], updatedDays: 8,
    },
    {
      id: "grace-chen", name: "Grace Chen", pronouns: "she/her", city: "Toronto", region: "ON", country: "Canada",
      badges: ["Board"], programs: [],
      headline: "Partner @ Maple Ridge Ventures. NEXT board member",
      about: "Early-stage investor in fintech and B2B software. Happy to give feedback on decks and fundraising plans.",
      ask: "Seed and Series A fundraising, pitch decks, fintech business models.",
      sectors: ["Fintech", "B2B SaaS"], skills: ["Fundraising", "Pricing"],
      lookingFor: { picks: [], text: "", updated: "" },
      openTo: ["Mentoring"],
      companies: [],
      role: "Partner, Maple Ridge Ventures", links: ["mapleridge.example"], updatedDays: 90,
    },
    {
      id: "omar-haddad", name: "Omar Haddad", pronouns: "he/him", city: "Montréal", region: "QC", country: "Canada",
      badges: ["Founder", "Current participant"], programs: [{ name: "NEXT Founders", year: 2026 }],
      headline: "Co-founder @ Souk Direct, wholesale ordering for independent grocers",
      about: "Independent grocers still order by phone and fax. We give them one app to order from 200+ suppliers.",
      ask: "Grocery and food distribution, marketplaces in Québec, bilingual products.",
      sectors: ["Marketplaces", "Consumer"], skills: ["Operations", "Marketing"],
      lookingFor: { picks: ["Customers", "Hires"], text: "Independent grocers in Québec; a first operations hire.", updated: "2 days ago" },
      openTo: ["Coffee chats", "Intro requests"],
      companies: [{ name: "Souk Direct", role: "Co-founder & COO", years: "2025 – present", status: "Active", site: "soukdirect.example" }],
      role: "COO, Souk Direct", links: ["soukdirect.example"], updatedDays: 2,
    },
    {
      id: "hannah-brooks", name: "Hannah Brooks", pronouns: "she/her", city: "San Francisco", region: "CA", country: "United States",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT 36", year: 2017 }],
      headline: "Head of Product @ a large dev-tools company. Founded Stackhouse (acquired 2022)",
      about: "Built Stackhouse in Toronto and moved to SF after the acquisition. Glad to help Canadian founders thinking about the US.",
      ask: "Moving to the US, product management, selling to developers, going through an acquisition.",
      sectors: ["B2B SaaS", "AI / ML"], skills: ["Product", "International expansion", "Hiring"],
      lookingFor: { picks: [], text: "", updated: "" },
      openTo: ["Coffee chats", "Mentoring"],
      companies: [{ name: "Stackhouse", role: "Founder & CEO", years: "2016 – 2022", status: "Acquired", site: "stackhouse.example" }],
      role: "Head of Product", links: ["linkedin.com/in/hannah-brooks-example"], updatedDays: 45,
    },
    {
      id: "ravi-patel", name: "Ravi Patel", pronouns: "he/him", city: "Waterloo", region: "ON", country: "Canada",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT AI", year: 2022 }],
      headline: "Exploring my next company. Previously founded Quillmark (legal AI)",
      about: "Ran Quillmark for two years before winding it down in 2024. Happy to talk openly about what went wrong.",
      ask: "Winding down a startup, legal tech, selling to law firms, LLM product design.",
      sectors: ["AI / ML", "Legal tech"], skills: ["Legal", "Regulatory", "Product"],
      lookingFor: { picks: ["Co-founder", "Advice"], text: "Talking to anyone working on AI for professional services.", updated: "3 weeks ago" },
      openTo: ["Coffee chats", "Mentoring", "Intro requests"],
      companies: [{ name: "Quillmark", role: "Founder & CEO", years: "2022 – 2024", status: "Closed", site: "quillmark.example" }],
      role: "Exploring", links: [], updatedDays: 20,
    },
    {
      id: "nadia-morin", name: "Nadia Morin", pronouns: "she/her", city: "Toronto", region: "ON", country: "Canada",
      badges: ["NEXT Staff"], programs: [],
      headline: "Program Manager at NEXT. Runs cohort onboarding",
      about: "I manage cohort intake and onboarding. If your program or cohort is wrong on your profile, let me know.",
      ask: "Program schedules, cohort details, applying to NEXT programs.",
      sectors: [], skills: ["Operations"],
      lookingFor: { picks: [], text: "", updated: "" },
      openTo: ["Intro requests"],
      companies: [],
      role: "Program Manager, NEXT Canada", links: [], updatedDays: 30,
    },
    {
      id: "chloe-martin", name: "Chloé Martin", pronouns: "she/her", city: "New York", region: "NY", country: "United States",
      badges: ["Alumni"], programs: [{ name: "NEXT 36", year: 2016 }],
      headline: "Startup lawyer @ Hollis & Pryce LLP. Helps Canadian founders set up in the US",
      about: "Corporate lawyer in New York. Most of my clients are Canadian startups raising from US investors or opening a US entity.",
      ask: "Delaware flips, US incorporation, cross-border fundraising documents, SAFEs, visas for founders (TN, O-1).",
      sectors: ["Legal tech", "Fintech"], skills: ["Legal", "Fundraising", "International expansion"],
      lookingFor: { picks: ["Partners"], text: "Meeting Canadian founders who are about to raise from US funds.", updated: "2 weeks ago" },
      openTo: ["Coffee chats", "Intro requests"],
      companies: [],
      role: "Associate, Hollis & Pryce LLP", links: ["linkedin.com/in/chloe-martin-example"], updatedDays: 12,
    },
    {
      id: "tomas-rivera", name: "Tomás Rivera", pronouns: "he/him", city: "Boston", region: "MA", country: "United States",
      badges: ["Founder", "Alumni"], programs: [{ name: "NEXT AI", year: 2023 }],
      headline: "Founder @ Cellwise Bio, machine learning for cell therapy manufacturing",
      about: "Spun out of a U of T lab and moved to Boston for the biotech ecosystem. Still hiring engineers in Toronto.",
      ask: "Biotech fundraising, moving a company to the US, FDA conversations, hiring across the border.",
      sectors: ["Biotech", "AI / ML"], skills: ["Fundraising", "Regulatory", "Hiring"],
      lookingFor: { picks: ["Investors", "Hires"], text: "Series A investors in bio-AI; ML engineers in Toronto.", updated: "1 week ago" },
      openTo: ["Coffee chats", "Intro requests", "Mentoring"],
      companies: [{ name: "Cellwise Bio", role: "Founder & CEO", years: "2023 – present", status: "Active", site: "cellwise.example" }],
      role: "CEO, Cellwise Bio", links: ["cellwise.example"], updatedDays: 6,
    },
  ];

  const posts = [
    { id: "p1", author: "jordan-lee", channels: ["Announcements"], pinned: true, hoursAgo: 30, votes: 18,
      title: "Welcome to the alumni platform (pilot)",
      body: "This is the new home for NEXT alumni. Fill in your profile so others can find you, and post questions here. Tag people with @ to pull them into a thread.",
      replies: [
        { id: "c1", author: "maya-okonkwo", hoursAgo: 28, votes: 7, body: "Great to have this. Already found two people I want to talk to.", replies: [
          { id: "c2", author: "jordan-lee", hoursAgo: 27, votes: 3, body: "Love that. @Maya Okonkwo let us know what would make the directory more useful.", replies: [] },
        ] },
      ] },
    { id: "p2", author: "priya-shah", channels: ["Fundraising", "Legal & finance"], hoursAgo: 5, votes: 24,
      title: "Who has raised from US funds as a Canadian company?",
      body: "We're starting our Series A process. Did you need to flip to a Delaware C-corp? What did legal cost you? @Chloé Martin curious what you see most often.",
      replies: [
        { id: "c3", author: "chloe-martin", hoursAgo: 4.5, votes: 19, body: "Not always required. Many US funds will invest in a Canadian company at Series A, but some fund documents require a Delaware entity. Budget roughly 6 to 10 weeks for a flip.", replies: [
          { id: "c4", author: "priya-shah", hoursAgo: 4, votes: 6, body: "Helpful, thank you. Do you know if the flip affects SR&ED credits?", replies: [
            { id: "c5", author: "chloe-martin", hoursAgo: 3.8, votes: 8, body: "It can. The Canadian subsidiary usually keeps doing the R&D so you keep the credits, but the structure matters. Worth a call with your accountant early.", replies: [
              { id: "c6", author: "tomas-rivera", hoursAgo: 3.5, votes: 4, body: "Can confirm. We kept our Toronto sub for exactly this reason.", replies: [
                { id: "c7", author: "priya-shah", hoursAgo: 3.2, votes: 2, body: "@Tomás Rivera did that make hiring in Toronto harder or easier?", replies: [
                  { id: "c8", author: "tomas-rivera", hoursAgo: 3, votes: 3, body: "Easier, honestly. Payroll and benefits stayed Canadian.", replies: [
                    { id: "c9", author: "priya-shah", hoursAgo: 2.8, votes: 1, body: "Perfect, that answers it.", replies: [] },
                  ] },
                ] },
              ] },
            ] },
          ] },
        ] },
        { id: "c10", author: "grace-chen", hoursAgo: 4, votes: 11, body: "From the investor side: we're flexible, but the lead usually decides. Happy to look at your deck in office hours.", replies: [] },
        { id: "c11", author: "hannah-brooks", hoursAgo: 3, votes: 5, body: "We flipped. Took about 8 weeks. Happy to share the checklist we used.", replies: [
          { id: "c12", author: "priya-shah", hoursAgo: 2.5, votes: 2, body: "Yes please! Sending you an intro request.", replies: [] },
        ] },
      ] },
    { id: "p3", author: "aisha-rahman", channels: ["Intro requests", "Hiring"], hoursAgo: 20, votes: 9,
      title: "Looking for a robotics or embedded co-founder",
      body: "Kitewing is looking for a technical co-founder. Anyone know strong embedded engineers in Vancouver who want to start something?",
      replies: [
        { id: "c13", author: "marcus-bell", hoursAgo: 12, votes: 4, body: "Not in Vancouver but happy to chat. Sending you an intro request.", replies: [] },
        { id: "c14", author: "etienne-gagnon", hoursAgo: 10, votes: 3, body: "@Marcus Bell you two should talk. Also try the embedded folks from the NEXT AI 2024 cohort.", replies: [] },
      ] },
    { id: "p4", author: "daniel-kwan", channels: ["Hiring"], hoursAgo: 50, votes: 6,
      title: "Hiring 2 sales engineers in Toronto",
      body: "Northwind Care is hiring. Health-tech experience is a plus. Referrals welcome.",
      replies: [] },
    { id: "p5", author: "omar-haddad", channels: ["General", "Legal & finance"], hoursAgo: 2, votes: 3,
      title: "Anyone selling a bilingual product in Québec?",
      body: "Trying to figure out what Bill 96 means for our app and marketing. Would love to hear what others did.",
      replies: [] },
    { id: "p6", author: "sam-whitehorse", channels: ["Events", "Fundraising"], hoursAgo: 72, votes: 11,
      title: "Hosting a fundraising AMA on Oct 22, bring questions",
      body: "Virtual, one hour. I'll answer anything about raising pre-seed and seed in Canada. RSVP on the Events page.",
      replies: [
        { id: "c15", author: "lena-novak", hoursAgo: 60, votes: 5, body: "Signed up. Can you cover SAFEs vs priced rounds?", replies: [
          { id: "c16", author: "sam-whitehorse", hoursAgo: 58, votes: 4, body: "Definitely. That's the most common question I get.", replies: [] },
        ] },
      ] },
  ];

  const events = [
    { id: "e1", title: "Vancouver founders coffee", date: "2026-10-15", start: "8:30", end: "10:00", mode: "In person", city: "Vancouver",
      location: "A café in Gastown (details after RSVP)", host: "aisha-rahman", nextHosted: false, capacity: 12, going: 7,
      description: "Casual coffee for founders in Vancouver. No agenda." },
    { id: "e2", title: "Fundraising AMA with Sam Whitehorse", date: "2026-10-22", start: "12:00", end: "13:00", mode: "Virtual", city: "",
      location: "Video link shared after RSVP", host: "sam-whitehorse", nextHosted: false, capacity: null, going: 41,
      description: "Ask anything about raising pre-seed and seed rounds in Canada." },
    { id: "e3", title: "Montréal climate founders breakfast", date: "2026-11-05", start: "8:00", end: "9:30", mode: "In person", city: "Montréal",
      location: "Venue to be confirmed", host: "etienne-gagnon", nextHosted: false, capacity: 20, going: 9,
      description: "For anyone building in climate or energy. Bilingual." },
    { id: "e4", title: "Toronto alumni mixer", date: "2026-11-26", start: "18:00", end: "20:30", mode: "In person", city: "Toronto",
      location: "Venue name, Toronto", host: "jordan-lee", nextHosted: true, capacity: 60, going: 38,
      description: "NEXT's fall alumni mixer. Drinks and food provided. Bring a founder friend from your cohort." },
    { id: "e5", title: "AI Program demo day", date: "2026-12-03", start: "14:00", end: "17:00", mode: "Virtual", city: "",
      location: "Livestream link shared after RSVP", host: "nadia-morin", nextHosted: true, capacity: null, going: 112,
      description: "The current NEXT AI cohort presents their companies." },
    { id: "e6", title: "US expansion office hours", date: "2026-10-08", start: "16:00", end: "17:00", mode: "Virtual", city: "",
      location: "Video link shared after RSVP", host: "chloe-martin", nextHosted: false, capacity: 10, going: 6,
      description: "Small-group office hours on incorporating or raising in the US." },
    { id: "e7", title: "NEXT Founders fall kickoff", date: "2026-10-20", start: "17:30", end: "20:00", mode: "In person", city: "Toronto",
      location: "Venue name, Toronto", host: "nadia-morin", nextHosted: true, capacity: 80, going: 54,
      description: "Welcome the new NEXT Founders cohort. Alumni mentors encouraged to attend." },
    { id: "e8", title: "Waterloo founders dinner", date: "2026-11-12", start: "18:30", end: "21:00", mode: "In person", city: "Waterloo",
      location: "Restaurant to be confirmed", host: "maya-okonkwo", nextHosted: false, capacity: 14, going: 11,
      description: "Dinner for founders in Waterloo Region. Pay your own way." },
  ];

  const reports = [
    { id: "r1", what: "Reply on \"Anyone selling a bilingual product in Québec?\"", reason: "Spam / self-promotion", by: "priya-shah", hoursAgo: 1 },
  ];

  return { TAXONOMY, people, posts, events, reports, hoursAgo };
})();
